lint:
  tags:
    - cvmfs
  script:
    - DHI_COMBINE_PYTHON_ONLY=1 source setup.sh
    - flake8 dhi --exclude dhi/tasks/postfit.py,dhi/scripts/postfit_plots.py

test:
  when: manual
  tags:
    - cvmfs
  script:
    - source setup.sh
    - law run dhi.tasks.test.TestPlots --version test_ci --print-status 1

build_docs_image:
  when: manual
  tags:
    - docker-image-build
  script: "echo Building image ${CI_REGISTRY_IMAGE}"
  variables:
    CONTEXT_DIR: "docs/docker"
    TO: "${CI_REGISTRY_IMAGE}:latest"
    NO_CACHE: "true"

deploy_docs:
  when: manual
  tags:
    - docker
  image: ${CI_REGISTRY_IMAGE}:latest
  environment:
    name: inference-${CI_COMMIT_REF_SLUG}
    url: ${PAGE_URL}${CI_ENVIRONMENT_SLUG}
    on_stop: delete_docs
  script:
    - test ! -z "${PAGE_ROOT}"
    - export FULL_PAGE_ROOT="${PAGE_ROOT}${CI_ENVIRONMENT_SLUG}"
    - echo "FULL_PAGE_ROOT is ${FULL_PAGE_ROOT}"
    - cd docs
    - mkdocs build
    - cd site
    - tar -czf site.tgz *
    - sshpass -v -p ${KRB_PASS} ssh -o "StrictHostKeyChecking=no" ${KRB_USER}@lxplus.cern.ch "[ ! -d ${FULL_PAGE_ROOT} ] && mkdir ${FULL_PAGE_ROOT} || rm -rf ${FULL_PAGE_ROOT}/*"
    - sshpass -v -p ${KRB_PASS} scp -o "StrictHostKeyChecking=no" site.tgz ${KRB_USER}@lxplus.cern.ch:${FULL_PAGE_ROOT}/site.tgz
    - sshpass -v -p ${KRB_PASS} ssh -o "StrictHostKeyChecking=no" ${KRB_USER}@lxplus.cern.ch "cd ${FULL_PAGE_ROOT}; tar -xzf site.tgz; rm site.tgz"

delete_docs:
  when: manual
  tags:
    - docker
  image: ${CI_REGISTRY_IMAGE}:latest
  environment:
    name: inference-${CI_COMMIT_REF_SLUG}
    action: stop
  script:
    - test ! -z "${PAGE_ROOT}"
    - export FULL_PAGE_ROOT="${PAGE_ROOT}${CI_ENVIRONMENT_SLUG}"
    - echo "FULL_PAGE_ROOT is ${FULL_PAGE_ROOT}"
    - sshpass -v -p ${KRB_PASS} ssh -o "StrictHostKeyChecking=no" ${KRB_USER}@lxplus.cern.ch "rm -rf ${FULL_PAGE_ROOT}"
