stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PLOT_GROUPS:
    value: "limits"
    options:
      - "limits"
      - "likelihoods"
      - "significances"
      - "pulls"
      - "exclusions"
      - "postfit"
      - "gof"
      - "eft_bm"
      - "eft_c2"
      - "studies"
      - "all"
    description: "The plot or plot group to test (see test.TestPlots for more info)."

lint:
  stage: build
  tags:
    - cvmfs
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - export DHI_COMBINE_PYTHON_ONLY="1"
    - source setup.sh
    - ./lint.sh

setup:
  stage: build
  when: manual
  tags:
    - cvmfs
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - yum install -y sshpass
    - mkdir -p data/examplecards
    - cd data/examplecards
    - sshpass -v -p ${KRB_PASS} scp -o "StrictHostKeyChecking=no" ${KRB_USER}@lxplus.cern.ch:/afs/cern.ch/user/m/mrieger/public/hh/inference/examplecards/v2.tgz cards.tgz
    - tar -xzf cards.tgz
    - cd ../..
    - export DHI_EXAMPLE_CARDS_BASE="${PWD}/data/examplecards"
    - source setup.sh
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: push
    paths:
      - data/

test:
  stage: test
  when: manual
  needs: ["setup"]
  tags:
    - cvmfs
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - export DHI_EXAMPLE_CARDS_BASE="${PWD}/data/examplecards"
    - source setup.sh
    - export test_cmd="law run test.TestPlots --version ci --plots ${PLOT_GROUPS} --campaign \"CI ${CI_COMMIT_SHORT_SHA}\" --file-types png,pdf"
    - eval "${test_cmd}"
    - eval "${test_cmd} --fetch-output 0,a,plots"
    - mkdir png
    - mkdir pdf
    - mv plots/*.png png
    - mv plots/*.pdf pdf
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - data/
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - png/*.png
      - pdf/*.pdf
    expire_in: 1 month

build_docs_image:
  stage: build
  when: manual
  tags:
    - docker-image-build
  script: "echo Building image ${CI_REGISTRY_IMAGE}"
  variables:
    CONTEXT_DIR: "docs/docker"
    TO: "${CI_REGISTRY_IMAGE}:latest"
    NO_CACHE: "true"

deploy_docs:
  stage: build
  when: manual
  tags:
    - docker
  image: ${CI_REGISTRY_IMAGE}:latest
  environment:
    name: inference-${CI_COMMIT_REF_SLUG}
    url: ${PAGE_URL}${CI_ENVIRONMENT_SLUG}
    on_stop: delete_docs
  script:
    - test ! -z "${PAGE_ROOT}"
    - export FULL_PAGE_ROOT="${PAGE_ROOT}${CI_ENVIRONMENT_SLUG}"
    - echo "FULL_PAGE_ROOT is ${FULL_PAGE_ROOT}"
    - cd docs
    - mkdocs build
    - cd site
    - tar -czf site.tgz *
    - sshpass -v -p ${KRB_PASS} ssh -o "StrictHostKeyChecking=no" ${KRB_USER}@lxplus.cern.ch "[ ! -d ${FULL_PAGE_ROOT} ] && mkdir ${FULL_PAGE_ROOT} || rm -rf ${FULL_PAGE_ROOT}/*"
    - sshpass -v -p ${KRB_PASS} scp -o "StrictHostKeyChecking=no" site.tgz ${KRB_USER}@lxplus.cern.ch:${FULL_PAGE_ROOT}/site.tgz
    - sshpass -v -p ${KRB_PASS} ssh -o "StrictHostKeyChecking=no" ${KRB_USER}@lxplus.cern.ch "cd ${FULL_PAGE_ROOT}; tar -xzf site.tgz; rm site.tgz"

delete_docs:
  stage: build
  when: manual
  tags:
    - docker
  image: ${CI_REGISTRY_IMAGE}:latest
  environment:
    name: inference-${CI_COMMIT_REF_SLUG}
    action: stop
  script:
    - test ! -z "${PAGE_ROOT}"
    - export FULL_PAGE_ROOT="${PAGE_ROOT}${CI_ENVIRONMENT_SLUG}"
    - echo "FULL_PAGE_ROOT is ${FULL_PAGE_ROOT}"
    - sshpass -v -p ${KRB_PASS} ssh -o "StrictHostKeyChecking=no" ${KRB_USER}@lxplus.cern.ch "rm -rf ${FULL_PAGE_ROOT}"
