stages:
  # - formatting
  - docs

# temporarily disabled
# black:
#   stage: formatting
#   tags:
#     - docker
#   image: python:3.7
#   script:
#     - pip install --no-cache-dir --upgrade pip
#     - pip install --no-cache-dir black==20.8b1
#     - black -l 100 --check --diff dhi

build_image:
  stage: docs
  when: manual
  tags:
    - docker-image-build
  script: "echo Building image ${CI_REGISTRY_IMAGE}"
  variables:
    CONTEXT_DIR: "docs/docker"
    TO: "${CI_REGISTRY_IMAGE}:latest"
    NO_CACHE: "true"

deploy_docs:
  stage: docs
  when: manual
  tags:
    - docker
  image: ${CI_REGISTRY_IMAGE}:latest
  script:
    - [ ! -z "${PAGE_ROOT}" ]
    - cd docs
    - mkdocs build --strict
    - cd site
    - tar -czf site.tgz *
    - sshpass -v -p ${KRB_PASS} ssh -o "StrictHostKeyChecking=no" ${KRB_USER}@lxplus.cern.ch "rm -rf ${PAGE_ROOT}/*"
    - sshpass -v -p ${KRB_PASS} scp -o "StrictHostKeyChecking=no" site.tgz ${KRB_USER}@lxplus.cern.ch:${PAGE_ROOT}
    - sshpass -v -p ${KRB_PASS} ssh -o "StrictHostKeyChecking=no" ${KRB_USER}@lxplus.cern.ch "cd ${PAGE_ROOT}; tar -xzf site.tgz; rm site.tgz"
